function run_all()
%RUN_ALL Regenerate every figure in the paper.
%   Open MATLAB, make this repository the current folder (or add it to the
%   path), and call RUN_ALL. Each figure script resolves its own paths, loads the
%   aggregated data from data/, and saves its output into figs/.
%
%   Each script is run in the base workspace and wrapped in try/catch so that a
%   failure in one figure does not stop the others.

figureScripts = { ...
    'fig1_natural_objects_chromatic_distribution', ...
    'fig2_hue_histogram', ...
    'fig3_human_thresholds', ...
    'fig5_decoding_acc', ...
    'fig6_human_meg', ...
    'fig7_network_thresholds', ...
    'fig8_human_network', ...
    'figS1_color_settings_meg', ...
    'figS2_prop_correct_meg', ...
    'figS3_vs_decoding_accuracy', ...
    'figS4_log_odds_ratio_meg', ...
    'figS5_decoding_acc_color_task', ...
    'figS6_decoding_acc_orientation_task', ...
    'figS7_taskonomy', ...
    'figS8_taskonomy_24tasks_layer', ...
    'figS9_network_layers'};

for iScript = 1:numel(figureScripts)
    name = figureScripts{iScript};
    fprintf('\n===== Running %s (%d/%d) =====\n', name, iScript, numel(figureScripts));
    try
        evalin('base', name);
    catch err
        fprintf(2, 'Skipped %s: %s\n', name, err.message);
    end
end

fprintf('\nDone. Figures written to %s\n', ...
    fullfile(fileparts(mfilename('fullpath')), 'figs'));
end
